// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.cats */
export type CatsId = string & { __brand: 'public.cats' };

/** Represents the table public.cats */
export default interface Cats {
  id: CatsId;

  lat: string;

  lng: string;

  creator_id: UsersId;
}

/** Represents the initializer for the table public.cats */
export interface CatsInitializer {
  id: CatsId;

  lat: string;

  lng: string;

  creator_id: UsersId;
}

/** Represents the mutator for the table public.cats */
export interface CatsMutator {
  id?: CatsId;

  lat?: string;

  lng?: string;

  creator_id?: UsersId;
}
