// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CatsId } from './Cats';

/** Identifier type for public.photos */
export type PhotosId = string & { __brand: 'public.photos' };

/** Represents the table public.photos */
export default interface Photos {
  id: PhotosId;

  uri: string;

  cat_id: CatsId | null;
}

/** Represents the initializer for the table public.photos */
export interface PhotosInitializer {
  id: PhotosId;

  uri: string;

  cat_id?: CatsId | null;
}

/** Represents the mutator for the table public.photos */
export interface PhotosMutator {
  id?: PhotosId;

  uri?: string;

  cat_id?: CatsId | null;
}
