// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CatsId } from './Cats';

/** Identifier type for public.reactions */
export type ReactionsId = string & { __brand: 'public.reactions' };

/** Represents the table public.reactions */
export default interface Reactions {
  id: ReactionsId;

  cat_id: CatsId | null;

  code: string;
}

/** Represents the initializer for the table public.reactions */
export interface ReactionsInitializer {
  id: ReactionsId;

  cat_id?: CatsId | null;

  code: string;
}

/** Represents the mutator for the table public.reactions */
export interface ReactionsMutator {
  id?: ReactionsId;

  cat_id?: CatsId | null;

  code?: string;
}
