// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  display_name: string;

  email: string;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  id: UsersId;

  display_name: string;

  email: string;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  display_name?: string;

  email?: string;
}
